# Generated by Django 4.0.5 on 2022-06-17 22:29

from django.db import migrations, models
import img.models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=img.models.upload_load),
        ),
    ]
